/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAOs.SorteoDAO;
import Entidades.Sorteo;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class VerSorteos extends javax.swing.JFrame {

    /**
     * Creates new form VerSorteos
     */
    public VerSorteos() {
        initComponents();
        cargarSorteos(); // Carga los sorteos cuando se inicia la ventana
    }
    
    
    
       // Método para cargar los sorteos en la tabla
    private void cargarSorteos() {
        try {
            SorteoDAO sorteoDAO = new SorteoDAO();
            List<Sorteo> sorteos = sorteoDAO.obtenerTodosSorteos();

            // Definir el modelo de tabla
            String[] columnas = {"ID Sorteo", "Precio Numero", "Total de numeros", "Estado"};
            Object[][] data = new Object[sorteos.size()][4];

            // Llenar los datos de los sorteos
            for (int i = 0; i < sorteos.size(); i++) {
                Sorteo sorteo = sorteos.get(i);
                data[i][0] = sorteo.getIdSorteo();
                data[i][1] = sorteo.getPrecioNumero();
                data[i][2] = sorteo.getRangoNumeros(); 
                data[i][3] = sorteo.getEstadoSorteo(); 
            }

            // Actualizar el modelo de la tabla
            jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnas) {
                Class[] types = new Class[]{
                        java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                        false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los sorteos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnVolver1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Sorteo", "Precio Numero", "Total de numeros", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnVolver1.setText("Volver");
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnVolver1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVolver1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        dispose(); // Cierra la pantalla
        // Aquí podrías redirigir al usuario a la nueva pantalla.
        MenuOrganizador a = new MenuOrganizador();
        a.setVisible(true);
    }//GEN-LAST:event_btnVolver1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
